### PR TITLE
Make MatrixTranspose_test build.

### PR DESCRIPTION
**Pull request by whchung**
Remove obsolete codes to make `MatrixTranspose_test` build again.

### CODE REVIEW

**Comment by whchung** [comment]
@eshcherb please help review this PR. This fixes `MatrixTranpose_test` to make it usable again.

**Comment by whchung** [comment]
@eshcherb  ping.

**Comment by eshcherb** [comment]
Could you try to uninstall roctracer from /opt/rocm

**Comment by whchung** [comment]
after revising to the tip of `roctracer` the issue seems to be no more. closing this PR.

**Pull request closed without merging**
